// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineApi.Data;

#nullable disable

namespace WineApi.Migrations
{
    [DbContext(typeof(WineContext))]
    partial class WineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_bin")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WineApi.Data.Bottle", b =>
                {
                    b.Property<int>("Bottleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bottleid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Bottleid"));

                    b.Property<int>("BinX")
                        .HasColumnType("int")
                        .HasColumnName("binX");

                    b.Property<int>("BinY")
                        .HasColumnType("int")
                        .HasColumnName("binY");

                    b.Property<sbyte>("Consumed")
                        .HasColumnType("tinyint")
                        .HasColumnName("consumed");

                    b.Property<DateTime?>("ConsumedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("consumed_date");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("depth")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Storageid")
                        .HasColumnType("int")
                        .HasColumnName("storageid");

                    b.Property<DateTime>("TsDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("ts_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("TsDate"));

                    b.Property<int>("Wineid")
                        .HasColumnType("int")
                        .HasColumnName("wineid");

                    b.HasKey("Bottleid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Storageid" }, "IX_tblBottles_storageid")
                        .HasDatabaseName("ix_bottle_storageid");

                    b.HasIndex(new[] { "Wineid" }, "IX_tblBottles_wineid")
                        .HasDatabaseName("ix_bottle_wineid");

                    b.ToTable("bottle", (string)null);
                });

            modelBuilder.Entity("WineApi.Data.Storage", b =>
                {
                    b.Property<int>("Storageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("storageid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Storageid"));

                    b.Property<string>("StorageAddr1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("storageAddr1");

                    b.Property<string>("StorageAddr2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("storageAddr2");

                    b.Property<string>("StorageCity")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("storageCity");

                    b.Property<string>("StorageDescription")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("storageDescription");

                    b.Property<string>("StorageState")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("storageState")
                        .IsFixedLength();

                    b.Property<int?>("StorageZip")
                        .HasColumnType("int")
                        .HasColumnName("storageZip");

                    b.Property<DateTime>("TsDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("ts_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("TsDate"));

                    b.HasKey("Storageid")
                        .HasName("PRIMARY");

                    b.ToTable("storage", (string)null);
                });

            modelBuilder.Entity("WineApi.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("KeyExpires")
                        .HasColumnType("datetime")
                        .HasColumnName("key_expires");

                    b.Property<string>("LastOn")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_on");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Key" }, "key_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("ix_users_key");

                    b.HasIndex(new[] { "Username" }, "username_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WineApi.Data.Wine", b =>
                {
                    b.Property<int>("Wineid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wineid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Wineid"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("TsDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("ts_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("TsDate"));

                    b.Property<string>("Varietal")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("varietal");

                    b.Property<string>("Vineyard")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vineyard");

                    b.Property<int?>("Vintage")
                        .HasColumnType("int")
                        .HasColumnName("vintage");

                    b.HasKey("Wineid")
                        .HasName("PRIMARY");

                    b.ToTable("wine", (string)null);
                });

            modelBuilder.Entity("WineApi.Data.Bottle", b =>
                {
                    b.HasOne("WineApi.Data.Storage", "Storage")
                        .WithMany("Bottles")
                        .HasForeignKey("Storageid")
                        .IsRequired()
                        .HasConstraintName("fk_bottles_storage");

                    b.HasOne("WineApi.Data.Wine", "Wine")
                        .WithMany("Bottles")
                        .HasForeignKey("Wineid")
                        .IsRequired()
                        .HasConstraintName("fk_bottles_wine");

                    b.Navigation("Storage");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineApi.Data.Storage", b =>
                {
                    b.Navigation("Bottles");
                });

            modelBuilder.Entity("WineApi.Data.Wine", b =>
                {
                    b.Navigation("Bottles");
                });
#pragma warning restore 612, 618
        }
    }
}
